<?php

namespace App\Entity;

use App\Repository\DeepSeaSiteRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DeepSeaSiteRepository::class)]
class DeepSeaSite extends Site
{
//    #[ORM\Id]
//    #[ORM\GeneratedValue]
//    #[ORM\Column]
//    private ?int $id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: true)]
    private ?Geography $geography = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: true)]
    private ?Campaign $campaign = null;

    #[ORM\Column(length: 255)]
    private ?string $nameOrNumberPrimary = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nameOrNumberSecondary = null;

//    public function getId(): ?int
//    {
//        return $this->id;
//    }

    public function getGeography(): ?Geography
    {
        return $this->geography;
    }

    public function setGeography(?Geography $geography): static
    {
        $this->geography = $geography;

        return $this;
    }

    public function getCampaign(): ?Campaign
    {
        return $this->campaign;
    }

    public function setCampaign(?Campaign $campaign): static
    {
        $this->campaign = $campaign;

        return $this;
    }

    public function getNameOrNumberPrimary(): ?string
    {
        return $this->nameOrNumberPrimary;
    }

    public function setNameOrNumberPrimary(string $nameOrNumberPrimary): static
    {
        $this->nameOrNumberPrimary = $nameOrNumberPrimary;

        return $this;
    }

    public function getNameOrNumberSecondary(): ?string
    {
        return $this->nameOrNumberSecondary;
    }

    public function setNameOrNumberSecondary(?string $nameOrNumberSecondary): static
    {
        $this->nameOrNumberSecondary = $nameOrNumberSecondary;

        return $this;
    }

    public function printName()
    {
        return parent::printName(); // TODO: Change the autogenerated stub
    }

    public function printLocality()
    {
        return parent::printLocality(); // TODO: Change the autogenerated stub
    }
}
