<?php

namespace App\Entity;

use App\Repository\GenusRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GenusRepository::class)]
class Genus extends Taxon
{
//    #[ORM\Id]
//    #[ORM\GeneratedValue]
//    #[ORM\Column]
//    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $genusName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $genusAuthority = null;

    #[ORM\Column(nullable: true)]
    private ?int $genusPublicationDate = null;

//    public function getId(): ?int
//    {
//        return $this->id;
//    }

    public function getGenusName(): ?string
    {
        return $this->genusName;
    }

    public function setGenusName(string $genusName): static
    {
        $this->genusName = $genusName;

        return $this;
    }

    public function getGenusAuthority(): ?string
    {
        return $this->genusAuthority;
    }

    public function setGenusAuthority(?string $genusAuthority): static
    {
        $this->genusAuthority = $genusAuthority;

        return $this;
    }

    public function printTaxonInfo(): string
    {
        return parent::printTaxonInfo(); // TODO: Change the autogenerated stub
    }

    public function getGenusPublicationDate(): ?int
    {
        return $this->genusPublicationDate;
    }

    public function setGenusPublicationDate(?int $genusPublicationDate): static
    {
        $this->genusPublicationDate = $genusPublicationDate;

        return $this;
    }
}
