<?php

namespace App\Entity;

use App\Repository\UnknownSiteRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UnknownSiteRepository::class)]
class UnknownSite extends Site
{
//    #[ORM\Id]
//    #[ORM\GeneratedValue]
//    #[ORM\Column]
//    private ?int $id = null;
//
//    public function getId(): ?int
//    {
//        return $this->id;
//    }
    public function printName()
    {
        return parent::printName(); // TODO: Change the autogenerated stub
    }

    public function printLocality()
    {
        $locality = 'unknown';

        return $locality;
    }

    public function printSiteInfo(): string
    {
        return 'unknown';
    }

}
